## Libraries and Constatnt declaration

In [2]:
import pandas as pd 
import numpy as np 
import streamlit as st 

data_TeamsRH = pd.read_excel("FICHE SALARIE MGS 01-2024- PART1.xlsx")
MSOC = 1000
META = 1001
Code_PO_MA = {    
    'ad dakhla': '73000',
    'ad darwa': '52000',
    'agadir': '80000',
    'aguelmous': '53000',
    'ahfir': '63050',
    'ain el aouda': '11000',
    'ait melloul': '80010',
    'ait ourir': '42050',
    'al aaroui': '91000',
    'al fqih ben çalah': '24000',
    'al hoceïma': '32000',
    'al khmissat': '23350',
    'al attawia': '35000',
    'arfoud': '53000',
    'azemmour': '24000',
    'aziylal': '22000',
    'azrou': '53100',
    'aïn harrouda': '20180',
    'aïn taoujdat': '34000',
    'berrchid': '27150',
    'ben guerir': '43150',
    'beni yakhlef': '26300',
    'berkane': '35000',
    'biougra': '83000',
    'bir jdid': '26100',
    'bou arfa': '21000',
    'boujad': '24350',
    'bouknadel': '16120',
    'bouskoura': '27160',
    'béni mellal': '23000',
    'casablanca': '20000',
    'casa': '20000',
    'chichaoua': '41000',
    'demnat': '45000',
    'el aïoun': '36000',
    'el hajeb': '25000',
    'el jadid': '24000',
    'el kelaa des srarhna': '40000',
    'errachidia': '52000',
    'fnidq': '92000',
    'fès': '30000',
    'guelmim': '81000',
    'guercif': '36000',
    'iheddadene': '60500',
    'imzouren': '93000',
    'inezgane': '80000',
    'jerada': '67250',
    'kenitra': '14000',
    'khemis sahel': '15150',
    'khénifra': '54000',
    'kouribga': '25000',
    'ksar el kebir': '20000',
    'larache': '92000',
    'laayoune': '70000',
    'marrakech': '40000',
    'martil': '93200',
    'mechraa bel ksiri': '28050',
    'mediouna': '26200',
    'mehdya': '28600',
    'meknès': '50000',
    'midalt': '52000',
    'missour': '54000',
    'mohammedia': '20800',
    'moulay abdallah': '54040',
    'moulay bousselham': '93250',
    'mrirt': '54010',
    'my drarga': '45000',
    'mdiq': '93200',
    'nador': '620',
    'oued zem': '59200',
    'ouezzane': '14200',
    'oujda-angad': '60000',
    'oulad barhil': '24200',
    'oulad tayeb': '14240',
    'oulad teïma': '82100',
    'oulad yaïch': '26450',
    'qasbat tadla': '15200',
    'rabat': '10000',
    'safi': '46000',
    'sale': '11000',
    'sefrou': '31000',
    'settat': '26000',
    'sidi bennour': '24250',
    'sidi qacem': '31050',
    'sidi slimane': '24000',
    'sidi smail': '60050',
    'sidi yahia el gharb': '12000',
    'sidi yahya zaer': '11030',
    'skhirate': '12050',
    'souk et tnine jorf el mellah': '26300',
    'tahla': '54000',
    'tameslouht': '40000',
    'tangier': '90000',
    'taourirt': '60300',
    'taza': '35000',
    'temara': '12000',
    'temsia': '30000',
    'tifariti': '70000',
    'tit mellil': '20100',
    'tinghir': '45800',
    'tétouan': '93000',
    'youssoufia': '46300',
    'zagora': '47900',
    'zawyat ech cheïkh': '14210',
    'zaïo': '60600',
    'Zeghanghane': '45000',
    'bejaad':'25060' }

condition = {
    'civ':{'monsieur':'$01',
     'mademoiselle':'$03',
     'madame':'$02'},
    'sexe':{
        'monsieur':'$1',
        'mademoiselle':'$2',
        'madame':'$2'
    },
    'civMarier':{'madame':'$01',
     'monsieur':'$02'},

    'sexeMarier':{
        'madame':'$1',
        'monsieur':'$2'
    },
    'sf':{
        'marié':'$02',
        "mariée":'$02',
        "marié(e)":'$02',
        'célibataire':'$01',
        'divorcée':'$03',
        'divorcé(e)':'$03',
        '':''
    },
    'CEMPLOI' :{
    'directeur général': '001',
    'chef comptable': '002',
    'coursier': '003',
    'technical support consultant': '004',
    'account manager': '005',
    'hr account manager': '006',
    'junior technical sales manager': '007',
    'content moderation supervisor': '008',
    'senior programe officer': '009',
    'head of north africa': '010',
    'area business head': '011',
    'digital fundraising specialist': '012',
    'user management advisor': '013',
    'content management advisor': '014',
    'family management advisor': '015',
    'vip user management advisor': '016',
    'femme de menage': '017',
    'territory s manager': '018',
    'rh and payroll specialist': '019',
    'program coordinator': '020',
    'comptable': '021',
    'hr specialist': '022',
    'event management advisor': '023',
    'agency management advisor': '024',
    'l&d specialist africa & m e': '025',
    'busines manager north africa': '026',
    'advisor': '027',
    'vip user management advisor': '028',
    'regional marketing manager eme': '029',
    'partnership manager - north af': '030',
    'directeur zone internationale': '031',
    'content management advisor': '032',
    'senior family management adv': '033',
    'associate project manager': '034',
    'program specialist learning': '035',
    'sales engineer': '036',
    'pubg mena prod manager': '037',
    'director of communication': '038',
    'dealer network development': '039',
    'lead specialist sourcing': '040',
    'in-country partnership special': '041',
    'area sales manager maghreb': '042',
    'content management advisor': '044',
    'family management advisor': '045',
    'hr service manager': '047',
    'consultant sirh': '048',
    'business development manager': '049',
    'managing director': '050',
    'market manager north africa': '051',
    'senior ams director': '052',
    'social media manager': '053',
    'regional sales manager': '054',
    'senior marketing specialist': '055',
    'président directeur général': '056',
    'directeur d’un département': '057',
    'directeur commercial': '058',
    'directeur financier': '059',
    'directeur administratif': '060',
    'directeur technique': '061',
    'directeur des ressources humaine': '062',
    'directeur d’une succursale': '063',
    'agent commercial': '064',
    'vrp': '065',
    'agent itinérant': '066',
    'président directeur général': '067',
    'directeur d\'une succursale': '068',
    'developpeur': '069',
    'responsable technique': '070',
    'channel sales manager': '071',
    'sales leader-sub safrica afric': '072',
    'client payroll officer': '073',
    'princing specialist': '074',
    'web scraper': '075',
    'senior software engineer': '076',
    'editor': '077',
    'senior customer success partne': '078',
    'backend engineer': '079',
    'qa test engineer': '080',
    'engineering manager': '081',
    'claim analyst': '082',
    'it system administrator': '083',
    'senior customer success partner': '085',
    'export manager mena': '086',
    'directeur administratif et fin': '087',
    'gestionnaire de paie': '088',
    'credit controller': '090',
    'consultant': '091',
    'territory sales executive': '092',
    'système engineering leader': '093',
    'client project leader': '094',
    'senior field marketing manager': '095',
    'sales manager': '096',
    'demand generation': '097',
    'prodact value promoter': '098',
    'directeur exécutif': '100',
    'ingénieur avant-vente sirh': '101',
    'directeur integration des solu': '102',
    'sales director': '103'
},
    'CATEGSP':{
    'directeur': '$cad',
    'cadre': '$cad',
    'agent de maitrise': '$agm',
    'employé': '$emp',
    'agent de maitrise': '$agm',
    'apprenti employé': '$app',
    'ouvrier': '$ouv',
    'stagiaire': '$sta',
    'stagiaire non rémunéré': '$stanr',
    '':''}
}

## Functions Definitions

In [3]:

#Cette Fonction pour faire un mappage entre RDD Sheets et le fichier Exceel fournit par le Client afin de créer une dataframe contain les données requis
def creer_dataframe(data_TeamsRH,c1:list,l:list):#name_table
    if len(c1) != len(l):
        return 'verifier c1 et c2'

    else :
        data={}
        length=data_TeamsRH.shape[0]
        for i,j in zip(l,c1) :
            if type(i)==list :
                data[j]=[condition[i[1]][k] for k in data_TeamsRH[i[0]] ]
                
            elif i=='':
                data[j]=['' for _ in range(length)]
            elif i in data_TeamsRH.columns:
                data[j]=[k for k in data_TeamsRH[i]]
            else:
                data[j]=[i for _ in range(length)]
        return pd.DataFrame(data)
    

def obtenir_noms_feuilles(fichier_excel):
    try:
        # Utiliser la fonction ExcelFile de pandas pour obtenir les noms des feuilles sans charger le fichier entier
        with pd.ExcelFile(fichier_excel) as xls:
            noms_feuilles = xls.sheet_names
        return noms_feuilles
    except Exception as e:
        print(f"Une erreur s'est produite : {str(e)}")
        return None

## Data PreProcessing

In [4]:
colums__=data_TeamsRH.columns
print(colums__)
columns_ = ['Matricule', 'Civilité', 'Nom', 'Prénom','Nombre d\'enfants', 'Date de naissance',
       'N  de carte de séjour/travail', 'Adresse', 'Complément d\'adresse',
       'Date d\'entrée poste', 'Nature du contrat',
        'Emploi occupé',
       'Catégorie du salarié', 'Salaire de Base MAD']
#data_TeamsRH.rename(columns=columns_, inplace = True)
#st.write(data_TeamsRH)
for i in data_TeamsRH.select_dtypes(exclude=['int', 'float']).columns:
    data_TeamsRH[i] = data_TeamsRH[i].apply(lambda x: x.strip().lower() if isinstance(x, str) else x)

data_TeamsRH = data_TeamsRH.dropna(subset=data_TeamsRH.columns, how='all')
data_TeamsRH["Date de naissance"] = data_TeamsRH["Date de naissance"].replace(" ", pd.NaT)
# Convertissez la colonne "Date de naissance" en format de date spécifique
format_date = "%d/%m/%Y"
data_TeamsRH['Date de naissance'] = data_TeamsRH['Date de naissance'].dt.strftime('%d/%m/%Y')
data_TeamsRH["Date d'entrée poste"] = data_TeamsRH["Date d'entrée poste"].dt.strftime('%d/%m/%Y')
   ####### st.write(data_TeamsRH,data_TeamsRH.dtypes)

#data=pd.read_excel('./Base salarié_15.02.2024__.xlsx',sheet_name='BDD COLLAB')
#data_TeamsRH['Salairee de base MAD']=data_TeamsRH['Salairee de base MAD'].fillna(0)
#Formatez la colonne 'DateNaissance' pour ne conserver que la date (jour, mois, année)
#st.write(data_TeamsRH)
data=data_TeamsRH.fillna('')

data["ADRVILLE"] = [str(i).split('-')[-1].replace(' ', '') if i != '' else '' for i in data["Complément d\'adresse"] ]
data["ADRCOMP"] = [str(i).split('-')[-2] if len(str(i).split('-'))>3  else '' for i in data["Complément d\'adresse"] ]
data["ADRCPOS"] = [Code_PO_MA[i] if i != '' else '' for i in data["ADRVILLE"]]
data["Complément d\'adresse"] = data["Adresse"]
data.rename({'Adresse':'Complément d\'adresse'})
#st.write(data)
#data=data.iloc[:-5]
data['Matricule']=data['Matricule'].astype(int)
data['Emploi occupé'] = data['Emploi occupé'].str.strip()
data['Emploi occupé'] = data['Emploi occupé'].str.lower()
data['Catégorie du salarié'] = data['Catégorie du salarié'].str.strip()
data['Catégorie du salarié'] = data['Catégorie du salarié'].str.lower()
################
#sexe =st.toggle('if columns <<Civilité>> exist select checkbox')
data=data.map(lambda x: x.lower() if isinstance(x, str) else x)
   
data.Nom=data.Nom.str.capitalize()
data.Prénom=data.Prénom.str.capitalize()

Index(['Matricule', 'Civilité', 'Nom', 'Prénom', 'Situation familiale',
       'Nombre d'enfants', 'Date de naissance', 'Numéro de Sécurité Sociale',
       'N  de carte de séjour/travail', 'Adresse', 'Complément d'adresse',
       'Date d'entrée poste', 'Date de début de contrat', 'Nature du contrat',
       'Date de fin de contrat', 'Motif de départ', 'Emploi occupé',
       'Catégorie du salarié', 'Etablissements', 'Salaire de Base MAD'],
      dtype='object')

## Implementation

In [5]:
tttt=  [        'S1IDE',
    'S1ADR',
    'S1CONJOINT',
    'S1ENFPC',
    'S1CONTRAT',
    'S2TYPECONTR',
    'S2ETA',
    'S2EMPLOI',
    'S2CATEG',
    'S2HORCONTR',
    'S2REMUNER',
    'S2ANALYT']
t1, t2,t3, t4,t5, t6,t7, t8,t9, t10,t11, t12= st.tabs(tttt)
with t1:
#xsS1IDE t1
    C=['MMAT','MRGL',	'MITEM' ,'MVERSION','CIVILITE',	'NOM1',	'Prénom1','NOMJF','SEXE',
                'DNAISS','LNNOMCOM','NUMNAT','NUMCNSS',	'SITFAM',	'LNPAYS_MND','LOCALIDNUMBER','ANCMAT']
    L=['Matricule','r1',0,0,['Civilité','civ'],'Nom','Prénom','',['Civilité','sexe'],
                'Date de naissance','','CIN','',['Situation familiale','sf'],'$MA','','']
    S1IDE=creer_dataframe(data, C,L)
    #{}
######
with t4:
    #S1ENFPC t4
    C=['MMAT','MITEM' ,'MVERSION',	'NOM1',	'NOM2',	'Prénom1',	'TITRE',	'SEXE',	'DNAISS',	'TYPEPC1',	'TYPEPC2' ]
    L=['Matricule',0,0,'Nom enf','','Prénom2','','$1','01/01/2020','','']
    S1ENFPC=creer_dataframe(data, C,L)
######
with t3:
   
        
    def S1CONJOINT_dataframe(data,C,L):
        
        l=[]
        for mat_ind ,mat in enumerate(data['Matricule']):
            #st.write(data[data['Matricule']==mat]['Situation familiale'])
            if (data.loc[data['Matricule'] == mat, 'Nombre d\'enfants'].iloc[0] != 0):
               
                for i in range(int(data['Nombre d\'enfants'][mat_ind])):
                    IJ={}
                    for i,j in zip(L,C):
                        if type(i)==list :
                          #  st.write(data[i[0]][mat_ind])
                            IJ[j]=condition[i[1]][data[i[0]][mat_ind]] 
                        elif i  in data.columns:
                            IJ[j]=data[i][mat_ind]
                        else:
                            IJ[j]=i
                        #st.write(IJ)
                    
                if data[data['Matricule']==mat]['Situation familiale'][mat_ind] in ['marié' ,'mariée']:
                    for ii in L:
                        if type(ii)==list :
                            IJ[j]=condition[ii[1]][data[ii[0]][mat_ind]]
                        elif ii in data.columns:
                            IJ[j]=data[ii]
                        else:   
                            IJ[j]=ii
                l.append(IJ)
            else  :
                if data[data['Matricule']==mat]['Situation familiale'][mat_ind] in ['marié' ,'mariée']:
                    IJ1={}
                    for inex,m in enumerate (L):
                        if type(m)==list :
                            g=data[m[0]][mat_ind]
                            #st.write('m',m,data[m[0]][data['Matricule']==mat][mat_ind])
                            IJ1[C[inex]]=condition[m[1]][g]
                        elif m in data.columns:
                            #o=[data['Matricule']==mat]
                            IJ1[C[inex]]=data[m][0]
                        else:   
                            IJ1[C[inex]]=m
                    l.append(IJ1)
            #st.write(l)
        ind=0
        df = pd.DataFrame(columns=C)
        for i in l:
            df.loc[ind]=i
            ind+=1
        return df
    #S1CONJOINT t3
    C=['MMAT','MITEM' ,'MVERSION','DDEB','DFIN','CIVILITE','NOM1','NOM2','Prénom1','TITRE','SEXE','DNAISS' ]
    L=['Matricule',0,0,'01/01/2000','',['Civilité','civMarier'],'Nom','','Prénom ','',['Civilité','sexeMarier'],'']
    #D=data[data['Situation familiale'].isin(['marié' ,'mariée'])]
    S1CONJOINT=S1CONJOINT_dataframe(data,C,L)#creer_dataframe(D, C,L) 
######
with t5:
    #S1CONTRAT t5
    C=['MMAT','MITEM' ,'MVERSION','DDEB','DFIN','MRGL','MSOC','CPERIOD','MOTIFENTREE','DSORTIE','DSOLDE',
        'MOTIFSORTIE','DANC1','DANC2','DANC3','DDEM','MOTCHG','DUE_CODESAL','DUE_CODEAR']
    L=['Matricule',1,0,"Date d'entrée poste",'','r1',MSOC,'','$02',
    '','','',"Date d'entrée poste","Date d'entrée poste","Date d'entrée poste",'','$empty','$empty','$empty']
    S1CONTRAT=creer_dataframe(data, C,L)
########
with t6:
    #S2TYPECONTR t6
    C=['MMAT','MITEM' ,'MVERSION',	'DDEB',	'DFIN',	'TYPCONTRAT',	'MCONTRAT',	'DADSUCODEDROIT']
    L=['Matricule',0,0,"Date d'entrée poste",'','$cdi',1,'']
    S2TYPECONTR=creer_dataframe(data, C,L)
########
with t7:
    #S2ETA t7
    C= ['MMAT','MITEM' ,'MVERSION', 'MCONTRAT', 'DDEB', 'DFIN', 'META', 'CODETRAVFE', 'SERVICE']
    L=['Matricule',0,0,1,"Date d'entrée poste",'',META,'$empty','$empty']
    S2ETA=creer_dataframe(data, C,L)    
#########
with t8:
    #S2EMPLOI t8
    C = ['MMAT','MITEM' ,'MVERSION', 'MCONTRAT', 'DDEB', 'DFIN', 'CEMPLOI']
    L=['Matricule',0,0,1,"Date d'entrée poste",'',['Emploi occupé','CEMPLOI']]########
    S2EMPLOI=creer_dataframe(data, C,L) 
##########
with t9:
    #S2CATEG t9
    C= ['MCLI', 'MMAT', 'MCONTRAT', 'MITEM' ,'MVERSION', 'MVERSION', 'DDEB',
            'DFIN', 'MOTCHG', 'CATEGSP', 'PRUDHOM_COLLEGE']
    L=['Z006','Matricule',1,0,0,0,"Date d'entrée poste",'','$empty',['Catégorie du salarié','CATEGSP'],'']
    S2CATEG=creer_dataframe(data, C,L)
###########
with t10:
#S2HORCONTR t10
    C=  ['MMAT', 'DDEB', 'DFIN', 'HORAIREAN', 'HORAIREMENS', 'HORAIREHEBDO', 'HORAIREJOUR',
        'CODETYPHOR', 'CODETPSTRAV', 'POURTPSTRAV', 'NBJOURAN', 'MODECAL', 'ACTDEFAUT', 
        'ACTMODE', 'PLANNING','MITEM' ,'MVERSION','MCONTRAT']
    L=['Matricule',"Date d'entrée poste",'',2288,191,44,8,'$me','','','','','','','$tcs',0,0,1]
    S2HORCONTR=creer_dataframe(data, C,L)   
#############
with t11:
#S2REMUNER t11
    C = ['MMAT', 'DDEB', 'DFIN', 'CREMUNER', 'MONTREMU', 'CDEVISE','MITEM' ,'MVERSION','MCONTRAT']
    L = ['Matricule',"Date d'entrée poste",'','$sbj','Salairee de base MAD','$mad',0,0,1]########
    S2REMUNER=creer_dataframe(data, C,L)
    #S2REMUNER.MONTREMU=S2REMUNER.MONTREMU.astype(str)
    #S2REMUNER['MONTREMU'] = S2REMUNER['MONTREMU'].astype(float)
    #S2REMUNER['MONTREMU'] = S2REMUNER['MONTREMU'].str.replace(' ', '').str.replace(',', '.').astype(float)

##########
with t12:
    #S2ANALYT t12
    C = ['MMAT', 'DDEB', 'DFIN','MITEM' ,'MVERSION','MCONTRAT']
    L = ['Matricule',"Date d'entrée poste",'',0,0,1]
    S2ANALYT=creer_dataframe(data, C,L)
###########
with t2:
    #S1ADR t2
    C  = [
                'MMAT',
                'DDEB',
                'DFIN',
                'ADRNUM',
                'ADRBIS',
                'ADRRUE',
                'ADRCOMP',
                'ADRVILLE',
                'ADRCPOS',
                'ADRTEL1',
                'ADRTEL2',
                'ADRMOB',
                'ADRMAIL',
                'ADRPAYS',
                ]
    L = ['Matricule',"Date d'entrée poste" ,'' ,'' , '','Complément d\'adresse', 'ADRCOMP','ADRVILLE','ADRCPOS', '', '', '','' , '$MA']
    S1ADR=creer_dataframe(data, C,L)
    
t= 'Output'
with pd.ExcelWriter(f'{t}.xlsx') as writer:
    S1IDE.to_excel(writer, sheet_name='S1IDE', index=False)
    S1ADR.to_excel(writer, sheet_name='S1ADR', index=False)
    S1CONJOINT.to_excel(writer, sheet_name='S1CONJOINT', index=False)
    S1ENFPC.to_excel(writer, sheet_name='S1ENFPC', index=False)
    S1CONTRAT.to_excel(writer, sheet_name='S1CONTRAT', index=False)
    S2TYPECONTR.to_excel(writer, sheet_name='S2TYPECONTR', index=False)
    S2ETA.to_excel(writer, sheet_name='S2ETA', index=False)
    S2EMPLOI.to_excel(writer, sheet_name='S2EMPLOI', index=False)
    S2CATEG.to_excel(writer, sheet_name='S2CATEG', index=False)
    S2HORCONTR.to_excel(writer, sheet_name='S2HORCONTR', index=False)
    S2REMUNER.to_excel(writer, sheet_name='S2REMUNER', index=False)
    S2ANALYT.to_excel(writer, sheet_name='S2ANALYT', index=False)